### ISSUE TITLE
Retrieve HTTP Response Headers

### ISSUE THREAD

**Issue by swelshh** [miyako/4d-plugin-curl-http#1]
Hello,

Is it be possible to get the http response headers after making a request?

If not, is that something that would be possible to add perhaps as a 2nd callback, for example:
error:=cURL_HTTP_Request(options ; request ; response {; curlInfo {; responseHeaders}})

**Comment by miyako** [comment]
at the library level there are 2 options:

[CURLOPT_HEADER](https://curl.haxx.se/libcurl/c/CURLOPT_HEADER.html) which will give you the full response (it will be your responsibility to decapitate the header from body) or [CURLOPT_HEADERFUNCTION](https://curl.haxx.se/libcurl/c/CURLOPT_HEADERFUNCTION.html) which is a callback function
