### ISSUE TITLE
HTTP/2 Request Error

### ISSUE THREAD

**Issue by spiffyguy** [miyako/4d-plugin-curl-http#2]
I am trying to send an HTTP/2 request to Apple Push Notifications and I am not sure how to send the post data...

This is currently my code (stripped of IDs, but should be readable)

OB SET($options;\
"URL";"https://api.development.push.apple.com:443/3/device/DEVICE_ID_HERE";\
"HTTP_VERSION";"2_PRIOR_KNOWLEDGE";\
"POST";1;\
"SSLCERT";Get 4D folder(Database folder)+"CERTS"+Folder separator+"CERTIFICATE_NAME_HERE")

ARRAY TEXT($headers;0)
APPEND TO ARRAY($headers;"apns-topic:APP_ID_HERE")
OB SET ARRAY($options;"HTTPHEADER";$headers)

C_BLOB($request;$response;$responseHeader)
$callback:=""

TEXT TO BLOB("{JSON PAYLOAD HERE}";$request;UTF8 text without length)

$error:=cURL_HTTP_Request (JSON Stringify($options);$request;$response;$callback;$responseHeader)

$textResponse:=BLOB to text($response;UTF8 text without length)
$textHeaderResponse:=BLOB to text($responseHeader;UTF8 text without length)

And I get a "Unexpected HTTP/1.x request" in the $response from Apple.

_Is CURLOPT_POSTFIELDS supported?_ (Nevermind POSTFIELDS should not be part of this for my needs)  Did I format the above correctly for HTTP/2?

Thanks,
- Matt

**Comment by miyako** [comment]
the plugin was compiled without libnghttp2. hold on.

**Comment by miyako** [comment]
CURLOPT_POSTFIELDS is not supported, it's mainly a CLI or scripting feature and not important for this plugin.

**Comment by miyako** [comment]
done in 3.1

**Comment by spiffyguy** [comment]
Hey Miyako, thank you!  FYI, I am currently on Mac v15 and communicating HTTP/2 with Apple's Push Notification server.  After this update, it is working well with this plugin!
